### ISSUE TITLE
LSF submission: Project name must be specified using bsub -P.

### ISSUE THREAD

**Issue by lauragails** [PacificBiosciences/pb-human-wgs-workflow-snakemake#128]
In order for our lsf cluster to accept a job using `workflow/process_smrtcells.lsf.sh`, I need the flag `bsub -P account-name`. account-name is static, so I can hard-code this. 

To fix this, I went into `profiles/lsf/config.yaml` and added `-P 'account-name' ` in the "cluster:" section. 

This isn't being recognized though. Is there something else I can do? 

**The good news**: `process_smrtcells.local.sh` does appear to be working, however I stopped it because I'd prefer to use lsf. 

Thank you for your guidance here!

**Comment by williamrowell** [comment]
We do something like this already for slurm, but we don't have an lsf cluster for testing, so it's really useful to get feedback like this.  I've added a patch, but I don't want to merge until it has been tested.

Could you test this by:
- making the changes to [profiles/lsf/config.yaml](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/pull/129/files#diff-04082b311521f788fb2633a55f202a9bf5a0abb47c68a76dfb72423a8e0b475f) described in #129 
- altering the [`ACCOUNT` line in variables.env](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/1feaed908a3c201ee9d8798f03b8e4253a9a51e3/variables.env#L3) to change it from `100humans` to your account name


In `variables.env`, you might also want to change:
- the TMPDIR on line 1 if your cluster uses a different scratch directory
- comment out line 9 (almost certainly)
- the default bsub partition/queue where you want to send most of your jobs goes on line 2
- if you plan on using a separate bsub partition with GPUs, that partition name goes on line 12
- if you plan on using GPUs, you'll probably need to modify the arguments on line 13 to those expected by bsub, something like `-gpu "mode=exclusive_process"`, but check with your HPC sysadmin if you're unfamiliar with these arguments

**Comment by lauragails** [comment]
Absolutely! Will let you know how it goes.

**Comment by lauragails** [comment]
We're closer but not there yet. After running I see 

`resources: mem_mb=192000, disk_mb=144043, tmpdir=/tmp, partition=$PARTITION, threads=1, out=./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.out, err=./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.err, extra=, account=account-name`

I made the changes in variables.env already, including commenting line 9 but the -P flag isn't recognized. I have to go to a seminar but will write further when I get back!

**Comment by williamrowell** [comment]
Before we dig deeper, just making sure:

Your profiles/lsf/config.yaml looks exactly like this:

```yaml
reason: true
rerun-incomplete: true
keep-going: true
printshellcmds: true
local-cores: 4
max-threads: 256
jobs: 500
max-jobs-per-second: 1
use-conda: true
conda-frontend: mamba
latency-wait: 120
use-singularity: true
singularity-args: '--nv '
cluster: bsub -cwd
              -P {resources.account}
              -q {resources.partition}
              -n {threads}
              -M {resources.mem_mb}
              -o {resources.out}
              -e {resources.err} {resources.extra}
default-resources:
  - account='$ACCOUNT'
  - partition='$PARTITION'
  - tmpdir=system_tmpdir
  - threads=1
  - mem_mb=8000*threads
  - out='./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.out'
  - err='./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.err'
  - extra=''
```

And the top of `variables.env` looks like:

```env
export TMPDIR=/tmp  # or your scratch dir
export PARTITION=compute   # or your default queue
export ACCOUNT=100humans   # or your account name
```

There's one more place where bsub is called, when launching the top level job submission scripts that launch snakemake (e.g., [process_smrtcells.lsf.sh](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/1feaed908a3c201ee9d8798f03b8e4253a9a51e3/process_smrtcells.lsf.sh#L1-L7).  We might need to add the params there as well, like:

```sh
#!/bin/bash
#BSUB -cwd
#BSUB -P account-name
#BSUB -L /bin/bash
#BSUB -q default
#BSUB -n 4
#BSUB -o ./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.out
#BSUB -e ./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.err
```

If you make this change and it still doesn't work, can you send me (either here or via email) any log files generated by the failed run.  If it generates a lot of logs, you can send a representative example, but I'd like to see at least the snakemake log and one of the failed bsub submission logs.
